services:
  - type: web
    name: erp_bom
    env: docker
    dockerfilePath: Dockerfile
    instanceCount: 1
    instanceType: free
    envVars:
      - key: PORT
        value: "8080"
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_URL
        sync: false